### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by deniskrizanovic** [stomita/sfdx-migration-automatic#5]
I have an installation issue that I don't know what to do with..

❯ npm install -g sfdx-migration-automatic
npm ERR! Cannot read property 'match' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     .... /.npm/_logs/2020-04-08T02_09_57_978Z-debug.log

This is what the error looks logfile looks like;

140 silly pacote version manifest for append-transform@1.0.0 fetched in 44ms
141 timing stage:rollbackFailedOptional Completed in 1ms
142 timing stage:runTopLevelLifecycles Completed in 12379ms
143 verbose stack TypeError: Cannot read property 'match' of undefined
143 verbose stack     at tarballToVersion (/usr/local/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:87:20)
143 verbose stack     at inflatableChild (/usr/local/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:99:22)
143 verbose stack     at BB.each (/usr/local/lib/node_modules/npm/lib/install/inflate-shrinkwrap.js:55:12)
143 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
143 verbose stack     at Object.gotValue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/

FYI .. updated Node to 13.12.0 .. just incase this was the issue, no change.

**Comment by dstdia** [comment]
Same here, node 13.9., npm is latest. Node and npm managed with nvm. Same error

**Comment by Szandor72** [comment]
Same here. node 13.10.1 current win10 machine.

**Comment by stomita** [comment]
I've updated the lib to 1.6.1 with dependent libs updated to latest, and it works fine in sfdx-cli/7.54.4-8ff9ba9cc5.
Be sure it should be installed through `sfdx plugins:install` command, not `npm install`.

**Comment by Szandor72** [comment]
Thanks for the swift response!

We tried npm because current readme tells us: 

> $ npm install -g sfdx-migration-automatic

**Comment by deniskrizanovic** [comment]
Is this really closed if the doco still says use npm to install?
